import React from 'react';
import ServerPaginatedTable from '@/components/server-paginated-table';
import { PaginationResponse } from '@/types/types';
import Slab, { SlabBody, SlabHeading } from '@/components/slab';
import { ServerPaginatedTableHeader } from '@/components/server-paginated-table';
import DateTimeDisplay from '@/components/date-time-display';
import { PinGenerator } from '@/types/models';
import { LinkButton } from '@/components/buttons';
import DashboardLayout from '@/layout/dashboard-layout';
import useInstitutionRoute from '@/hooks/use-institution-route';
import { HStack, Icon, IconButton, Tooltip } from '@chakra-ui/react';
import { CloudArrowDownIcon } from '@heroicons/react/24/outline';

interface Props {
  pinGenerators: PaginationResponse<PinGenerator>;
}

export default function ListPinGenerators({ pinGenerators }: Props) {
  const { instRoute } = useInstitutionRoute();
  const headers: ServerPaginatedTableHeader<PinGenerator>[] = [
    {
      label: 'Num of Pins',
      value: 'num_of_pins',
    },
    {
      label: 'Generated By',
      value: 'user.full_name',
    },
    {
      label: 'Comment',
      value: 'comment',
    },
    {
      label: 'Generated At',
      value: 'created_at',
      render: (row) => <DateTimeDisplay dateTime={row.created_at} />,
    },
    {
      label: 'Action',
      render: (row) => (
        <HStack>
          <LinkButton
            variant={'link'}
            href={instRoute('pin-generators.show', [row.id])}
            title="View Pins"
          />
          <Tooltip label={'Download Pins'}>
            <IconButton
              aria-label="Download Pins"
              icon={<Icon as={CloudArrowDownIcon} />}
              colorScheme="brand"
              size={'md'}
              as={'a'}
              href={instRoute('pin-generators.download', [row.id])}
              variant={'ghost'}
            />
          </Tooltip>
        </HStack>
      ),
    },
  ];

  return (
    <DashboardLayout>
      <Slab>
        <SlabHeading
          title="Generated Pins"
          rightElement={
            <LinkButton
              label="Generate Pin"
              href={instRoute('pin-generators.create')}
            />
          }
        />
        <SlabBody>
          <ServerPaginatedTable
            scroll={true}
            headers={headers}
            data={pinGenerators.data}
            keyExtractor={(row) => row.id}
            paginator={pinGenerators}
          />
        </SlabBody>
      </Slab>
    </DashboardLayout>
  );
}
