<?php

return [
  'source_url' =>
    'https://help.bulksmsnigeria.com/article/show/92243-blocked-words',

  /*
   * The provider states that operators do not publish a complete, permanent
   * list. Keep this published list here as a conservative pre-send denylist;
   * update it when the provider changes its guidance.
   */
  'blocked_sender_ids' => [
    'FBI',
    'CIA',
    'Notice',
    'Admission',
    'Jonathan',
    'Interpol',
    'Interp0l',
    '1nterp0l',
    'EFCC',
    'ETISALAT',
    'Glo NG',
    'MTN',
    'MTNNG',
    'MTNB0NUS',
    '+MTNNG',
    "M'T'NNG",
    'MTN Nig',
    'MTN-Nigeria',
    'CBN',
    'FGN',
    'NOLLYWOOD',
    'AIRTEL',
    'GL0NG',
    'GLO',
    'GTBank',
    'GTB Ekenwan',
    'FBN Jos',
    'FBN',
    'Uselu',
    'Ekenwa',
    'Yellow',
    'MFB',
    'FCMB',
    'Patrick',
    'orange',
    'Zenith',
    'Zenith Bank',
    'Zen',
    'Bank',
    'Access',
    'Access bank',
    'Prophetic',
    'A.P.C',
    'P.D.P',
    'Election',
    'L.P'
  ],

  'blocked_words' => [
    'congrats',
    'congratulations',
    'wow',
    'love',
    'sex',
    'promo',
    'fuck',
    'yellow',
    'raffle',
    'globacom',
    'win',
    'promotion',
    'promotions',
    'winning',
    'invitation',
    'won',
    'wada',
    'yell0w',
    'survey',
    'surveyor',
    'btc or eth',
    'hurray',
    'financial',
    'code',
    'otp',
    'verification',
    'whatsapp',
    'facebook',
    'twitter',
    'instagram',
    'yahoo.com',
    'apc',
    'pdp',
    'vote',
    'ydp',
    'election',
    'elect',
    'invite',
    'pos',
    'app',
    'admission',
    'remind',
    'nin',
    'bvn',
    'uba',
    'gtb',
    'fcmb',
    'atm',
    'card',
    'account',
    'password',
    'token',
    'google',
    'google forms',
    'link',
    'bet'
  ],

  'blocked_characters' => ['&', '$', '#', '@'],
  'max_sender_length' => 11,
  'max_message_length' => 1530
];
